### PR TITLE
Enable and fix CI on Windows

### PR DESCRIPTION
**Pull request by miller-alex**
I've been playing around with CI on Windows and fixed a bunch of build failures with MSVC in the process.
You may want to look over the changes before this gets merged into main.

There are still a few loose ends:
* The code uses `#ifdef _WIN32` or similar to provide alternatives for functionality missing with MSVC. Some of these may not apply to all toolchains on Windows, so adding configure checks may be a better alternative.
* Some of the tests fail on Windows (tests are broken, `trrntzip` seems to work).

4 tests fail because zip file names are printed with `\` as dir separator instead of `/`. Do you have a suggestion how to handle that with `nihtest`? There's `stderr-replace` for stderr (and it would be great to have an equivalent for stdout and files), we can use `[comparator-preprocessors]` or `[comparators]` for files, but what about stdout? Is there any way to filter/redirect/ignore stdout or do we need a wrapper around `trrntzip`?

It's more complicated with `directories-2-d.test`. Removed directories may be listed in any order with `trrntzip -d` because they all compare equal when the entries get sorted, i.e., it depends on the implementation details of `qsort()`. The test isn't reliable on any operating system, MSVC's C runtime is just the first to trigger the issue. It's probably best to ignore stdout and just compare the zips.

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
The pull request looks good to me, thank you!
As for your questions:
- we'll add stdout-replace to nihtest
- but, I think that the messages should not be different on Windows than on Linux - both should use '/' as a directory separator since that's what the directory separator inside zip archives *is*.
Does changing the output to always use `/` fix the five tests on Windows with the nihtest 1.5?

**Comment by miller-alex** [comment]
The directory separator inside the archives is always `/`, it's the separator in the path to the zip files themselves that differs.
And it seems to be the only difference for the four affected tests.

As noted above, the fifth test fails because the order of "Directory ${dir}/ Removed" messages is undefined with `-d`.
We could switch to a total order for sorting to get deterministic output, though it isn't relevant for anything but testing.
[Update:] Changed `BasenameCompare()`, flaky test should be fixed.

**Comment by miller-alex** [comment]
Just in case, here's the output from the failing CI tests on Windows (from the run before I marked them as failing).
The other test is already fixed.
```
      Start  6: cli-q.test
 6/26 Test  #6: cli-q.test .......................***Failed    0.10 sec
output differs:
-Rezipping - dir/another.zip
+Rezipping - dir\another.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
-Rezipping - dir/sub/one.zip
+Rezipping - dir\sub\one.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
cli-q -- FAIL: output

      Start  7: cli-s.test
 7/26 Test  #7: cli-s.test .......................***Failed    0.10 sec
output differs:
-Rezipping - dir/another.zip
+Rezipping - dir\another.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
-Skipping, already TorrentZipped - dir/moretorrentzip.zip
+Skipping, already TorrentZipped - dir\moretorrentzip.zip
cli-s -- FAIL: output

      Start 18: recurse.test
18/26 Test #18: recurse.test .....................***Failed    0.10 sec
output differs:
-Rezipping - dir/CaSe.ZiP
+Rezipping - dir\CaSe.ZiP
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
-Rezipping - dir/sub/small.zip
+Rezipping - dir\sub\small.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
recurse -- FAIL: output

      Start 19: recursive.test
19/26 Test #19: recursive.test ...................***Failed    0.10 sec
output differs:
-Rezipping - dir/another.zip
+Rezipping - dir\another.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
-Skipping, already TorrentZipped - dir/moretorrentzip.zip
-Rezipping - dir/sub/one.zip
+Skipping, already TorrentZipped - dir\moretorrentzip.zip
+Rezipping - dir\sub\one.zip
 --------------------------------------------------
 Adding - test.txt (31 bytes)...Done
 --------------------------------------------------
 Rezipped 1 compressed file totaling 31 bytes.
-Skipping, already TorrentZipped - dir/sub/torrentzip.zip
+Skipping, already TorrentZipped - dir\sub\torrentzip.zip
recursive -- FAIL: output
```

**Comment by 0-wiz-0** [comment]
nihtest-1.6.0, just released, has added support for `stdout-replace` - let me know if there are any problems with that!

**Comment by miller-alex** [comment]
Thanks, fixed the tests that were failing on Windows using `stdout-replace`.

(Btw, I noticed `nihtest -q` throws a traceback when a test fails.)

**Comment by 0-wiz-0** [comment]
Thanks for updating the Windows tests!
And also thanks for letting me know, I've reproduced the `-q` problem and added a test for it, we'll fix it soon.

**Pull request merged**
